---
- name: Quick web server setup
  hosts: localhost
  become: true
  tasks:
    - name: Install Apache
      ansible.builtin.package:
        name: httpd
        state: present

    - name: Start and enable Apache service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Create a simple HTML file
      ansible.builtin.lineinfile:
        path: /var/www/html/index.html
        line: "<h1>Welcome to the Web Server!</h1>"
        create: true
